name: Publishing

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Capture Artefacts
        if: ${{ runner.os == 'ubuntu-latest' && runner.java == '17' }}
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/
          name: Jars

      - name: Upload Assets
        if: ${{ runner.os == 'ubuntu-latest' && runner.java == '17' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lib/build/libs/neutron-${{ env.VERSION }}.jar
          asset_name: Neutron-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Publish to GitHub packages
        if: ${{ runner.os == 'ubuntu-latest' && runner.java == '17' }}
        run: ./gradlew publish